apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
    field.cattle.io/creatorId: user-vqwmp
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/secure-backends: "true"
  generation: 1
  labels:
    cattle.io/creator: norman
  name: botcms-back
  namespace: botcms
  selfLink: /apis/extensions/v1beta1/namespaces/botcms/ingresses/botcms-back
#  uid: a89b1a01-694c-11e9-9269-de1c3c6a503b
spec:
  rules:
    - host: api.botcms.siworks.org
      http:
        paths:
          - backend:
              serviceName: botcms-back
              servicePort: 3000
  tls:
    - hosts:
        - api.botcms.siworks.org
      secretName: botcms-back-siworks-crt
